spring:
  data:
    mongodb:
      uri:  "mongodb+srv://admin:odtech2023@odtech-cluster.ikg5q7r.mongodb.net/?retryWrites=true&w=majority"
      database: odtechDB
server:
  servlet:
    context-path: /api